[versions]
agp = "8.6.0"
kotlin = "2.0.0"
coreKtx = "1.16.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
lifecycleRuntimeKtx = "2.9.2"
activityCompose = "1.10.1"
composeBom = "2024.04.01"
navigation = "2.7.7"
coil = "2.4.0"
retrofit = "2.9.0"
converter-gson = "2.9.0"
viewmodel-compose = "2.7.0"
runtime-ktx = "2.7.0"
coroutines = "1.7.3"
hilt = "2.56.2"
hilt-navigation = "1.0.0"
storage = "1.5.0"
calendar = "1.1.1"
datetime = "0.6.0"
protoliteWellKnownTypes = "18.0.1"
room = "2.7.2"
ksp = "2.0.0-1.0.21"
datastore = "1.1.7"
runtimeLivedata = "1.9.0"
paging = "3.3.2"
paging-compose = "1.0.0-alpha18"
oss = "17.1.0"
google-services = "4.4.4"
firebase-bom = "34.6.0"
converter-scalars = "2.9.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation" }
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
androidx-retrofit2 = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
androidx-converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "converter-gson" }
androidx-lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "viewmodel-compose" }
androidx-lifecycle-runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "runtime-ktx" }
coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
hilt = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
hilt-navigation = {group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hilt-navigation"}
androidx-storage = { group = "androidx.test.services", name = "storage", version.ref = "storage" }
calendar = { group = "com.maxkeppeler.sheets-compose-dialogs", name = "calendar", version.ref = "calendar" }
datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "datetime" }
protolite-well-known-types = { group = "com.google.firebase", name = "protolite-well-known-types", version.ref = "protoliteWellKnownTypes" }
room-runtime = {group = "androidx.room", name = "room-runtime", version.ref= "room"}
room-compiler = {group = "androidx.room", name = "room-compiler", version.ref= "room"}
room-rxjava3 = {group = "androidx.room", name = "room-rxjava3", version.ref= "room"}
room-testing = {group = "androidx.room", name = "room-testing", version.ref= "room"}
room-paging = {group = "androidx.room", name = "room-paging", version.ref= "room"}
room-guava = {group = "androidx.room", name = "room-guava", version.ref= "room"}
room-ktx = {group = "androidx.room", name = "room-ktx", version.ref= "room"}
datastore = {group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore"}
androidx-runtime-livedata = { group = "androidx.compose.runtime", name = "runtime-livedata", version.ref = "runtimeLivedata" }
paging = {group = "androidx.paging", name = "paging-runtime", version.ref = "paging"}
paging-compose = {group = "androidx.paging", name = "paging-compose", version.ref = "paging-compose"}
oss = {group = "com.google.android.gms", name = "play-services-oss-licenses", version.ref = "oss"}
firebase-bom = {group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase-bom"}
firebase-analytics = {group = "com.google.firebase", name = "firebase-analytics"}
firebase-messaging = { group = "com.google.firebase", name = "firebase-messaging" }
converter-scalars = {group = "com.squareup.retrofit2", name = "converter-scalars", version.ref = "converter-scalars"}

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt"}
ksp = {id = "com.google.devtools.ksp", version.ref = "ksp"}
google-services = {id = "com.google.gms.google-services", version.ref = "google-services"}
